
# Loader Metadata
modLoader="javafml" # mandatory
loaderVersion="[28,)" # mandatory
issueTrackerURL="https://github.com/alcatrazEscapee/last-supper" # optional

# Ore Veins
[[mods]] # mandatory
    modId="lastsupper" # mandatory
    version="${file.jarVersion}" # mandatory
    displayName="Last Supper" # mandatory
    #updateJSONURL="http://myurl.me/" #optional
    displayURL="https://github.com/alcatrazEscapee/last-supper" #optiona
    #logoFile="examplemod.png" #optional
    #credits="" #optional
    authors="AlcatrazEscapee" #optional
    description='''
    This mod adds the last supper you will ever need, albeit until you die.

    The Last Supper is a special food item. Once you consume it, you will never need to consume any other food again. You will have eternally full hunger. This buff is lost when you die. Note that it will not give you infinite saturation, so it can be a trade-off.
    '''

# dependencies
[[dependencies.oreveins]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.oreveins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,)"
    ordering="NONE"
    side="BOTH"